name: Java CI/CD Workflow

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Action 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Action 2: Set up Java
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    # Action 3: Compile the code
    - name: Build with Maven
      run: mvn -B compile --file pom.xml

    # Action 4: Run tests
    - name: Test with Maven
      run: mvn -B test --file pom.xml